### ISSUE TITLE
Automatically export

### ISSUE THREAD

**Issue by fvilers** [CruelDrool/GuildRosterExport#1]
Hi,

This is a nice addon. I'd like to automate the roster management of our guild with it and I think it could be cool if the addon would export the roster automatically on connection or disconnection. It could write to a "saved variables" file. Then I'd write a small automation batch to upload it to our spreadsheet.

What do you think ?

Cheers !

**Comment by CruelDrool** [comment]
Yea, I'm intrigued. Did a quick test, and it certainly is possible. The export would happen on something like PLAYER_ENTERING_WORLD. WoW does a save to the saved variable file whenever you reload UI, log out/exits or disconnects.

I assume you can handle the resulting Lua string output in WTF\Account\<AccountName>\SavedVariables\GuildRosterExport.lua

Let me get back to you.

**Comment by CruelDrool** [comment]
Try to clone this branch: https://github.com/CruelDrool/GuildRosterExport/tree/export-on-logon

This is just us testing it out. Added an option called "Auto export at logon" under "Global" there. The output is saved in the file I mentioned earlier, inside a Lua table. 

```Lua
GuildRosterExportDB = {
	["profiles"] = {
		["Character - ServerName"] = {
			["autoExportSave"] = "<Export data>",
		},
	},
}
````

Name of setting and such may change should I go ahead with this.

**Comment by fvilers** [comment]
It works great ! I will now extract the produced JSON string and upload it. Thanks ;-)

**Comment by CruelDrool** [comment]
Some heads up. I tweaked the name of the setting a bit. From `autoExportLogon` to `autoExport`. This means that it will be turned off for you. The place where the export is stored is the same, though.
